In [1]:
from datar.datasets import mtcars, iris
from datar.all import *

from nb_helpers import nb_header
nb_header(arrange)

### # arrange

##### orders the rows of a data frame by the values of selected columns.

The original API:
https://dplyr.tidyverse.org/reference/arrange.html

##### Args:
&emsp;&emsp;`_data`: A data frame
&emsp;&emsp;`*series`: Variables, or functions of variables.
&emsp;&emsp;&emsp;&emsp;Use desc() to sort a variable in descending order.

&emsp;&emsp;`_by_group`: If TRUE, will sort first by grouping variable.
&emsp;&emsp;&emsp;&emsp;Applies to grouped data frames only.

&emsp;&emsp;`**kwargs`: Name-value pairs that apply with mutate

##### Returns:
&emsp;&emsp;An object of the same type as _data.
&emsp;&emsp;The output has the following properties:
&emsp;&emsp;&emsp;&emsp;All rows appear in the output, but (usually) in a different place.
&emsp;&emsp;&emsp;&emsp;Columns are not modified.
&emsp;&emsp;&emsp;&emsp;Groups are not modified.
&emsp;&emsp;&emsp;&emsp;Data frame attributes are preserved.

In [2]:
arrange(mtcars, f.cyl, f.disp)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4

In [3]:
mtcars >> arrange(desc(f.disp))

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1

In [4]:
by_cyl = mtcars >> group_by(f.cyl)
by_cyl >> arrange(desc(f.wt)) >> ungroup()

     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2

In [5]:
by_cyl >> arrange(desc(f.wt), _by_group=True) >> ungroup()

     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4

In [6]:
# use subscription for f-expression
def tidy_eval_arrange(_data, var):
  return _data >> arrange(f[var])
  
tidy_eval_arrange(mtcars, 'mpg')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1

In [7]:
iris >> arrange(across(starts_with("Sepal")))

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
13            4.3          3.0           1.1          0.1     setosa
8             4.4          2.9           1.4          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
42            4.4          3.2           1.3          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

In [8]:
iris >> arrange(across(starts_with("Sepal"), desc))

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
131           7.9          3.8           6.4          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa

[150 rows x 5 columns]